### ISSUE TITLE
QuickPlugin 那个nsi脚本不能支持qml的界面出来。

### ISSUE THREAD

**Issue by Calvin-Shen** [graycatya/NsCatGrayQt-Plugin#2]
应该是环境还差东西，界面加载不起来。

**Comment by graycatya** [comment]
qt quick 做安装界面，我是不推荐的，因为dll需要依赖qt下的Qt\5.15.2\msvc2019_64目录中的qml，plugins这些依赖，导致安装包会变大，建议直接用widget做安装界面更合适。quickplugin是我对qt quick的一种尝试。
